### PR TITLE
Adding the Bible in NKJV and SVD

### PR DESCRIPTION
**Pull request by beesh-bigori**

### CODE REVIEW

**Comment by dbishai** [comment]
On further examination, everything looks great. I like keeping all of the verses in one text object where each verse is an array element.

It doesn't seem like the Arabic unicode characters are being decoded properly. Besides that if you could replace white space in the directory names with underscores that would be good.

**Comment by dbishai** [comment]
Oh and also maybe append "\n" to the end of every file.

**Comment by beesh-bigori** [comment]
The Arabic is written in the JSON Unicode notation, do you prefer it to be written as plan UTF-8 characters instead?
e.g. 'ي' instead of \u064A
Notice that this means the code that opens the JSON files for read later has to deal with them as UTF-8 and deal with the UTF-8 BOM (the first three bytes of the file)

**Comment by dbishai** [comment]
So if we have escaped Unicode characters, the advantages are human readable files and not having to escape at render time. The downside is that the file sizes will be larger. Right?

**Comment by beesh-bigori** [comment]
Two options:
ONE:
**Use the JSON escape notation (e.g. each letter is like `\u064A`)**
Each letter will use six bytes on disk.
Advantage: easier reading by code

TWO
**Use UTF-8 format for JSON files: (e.g. each letter is like `ي`)**
Each letter will use three bytes on disk
Advantages:
Human readable in the JSON file
Less file size

**Comment by dbishai** [comment]
Oh whoops meant non-escaped characters. OK, thanks for clarifying.

We definitely want option 2 then which is consistent with all of the other documents. Thanks for your hard work!

**Comment by beesh-bigori** [comment]
No problems ;)

**Pull request merged**
